# This file was generated by GoReleaser. DO NOT EDIT.
cask "zasper" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "0ffe7b730e9f94426c875c9a677a2ec4bd4ff5af0cd37c00259757463c1a8fd6"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "881f8d3eb41786e12a58ea44078d3f0ac4b34a0511fd91784ecc0c5b2971a7ef"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "42b7c725bb83c69abf82427e46d73f7992bdf2f03e83af0ffaa18bbd76452000"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "55fd3c962bd4872c3341226f4bbe6e1ff7020f0604990902f6b13d8f2c57e67e"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-amd64.tar.gz"
    end
  end

  name "zasper"
  desc "High Performance IDE for Jupyter Notebooks"
  homepage "https://zasper.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zasper"

  # No zap stanza required

  caveats <<~EOS
    Zasper needs a Jupyter kernel to run notebooks:
      pip install ipykernel
  EOS
end
