# This file was generated by GoReleaser. DO NOT EDIT.
cask "zasper" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "6adf4070467034180be33a32ebea06b17f4e5ba0b8a812299e6058f1b3f52009"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "f3318ab5daf4feb02cb7b7e0a754e3bac5d92043cc454b83d8019a5ccd6e9c29"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "972f4980aa4aaadcb9db347e96666e7fc45856e3b2e88515a4717d0617854f61"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "72c8216303a4ad62823961650744008335c13b6b73ab1ad5ebdd038fda34d604"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-amd64.tar.gz"
    end
  end

  name "zasper"
  desc "High Performance IDE for Jupyter Notebooks"
  homepage "https://zasper.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zasper"

  # No zap stanza required

  caveats <<~EOS
    Zasper needs a Jupyter kernel to run notebooks:
      pip install ipykernel
  EOS
end
