# This file was generated by GoReleaser. DO NOT EDIT.
cask "zasper" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "2aa33dcfdc056875636c6011cf0c3f3f5e936d04481ecf847dfa2e1fe2b43a7a"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "6e759084304d82565069743d6b9e943adeea7e05d903b2b6514b881de54cb255"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3d26832b20c9920ae21874af8e46b91d1465eb893cc12fc5bb01011e605e79b5"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "d40cc56b79271d24f68b02ddbd656f976bd2ae2d3f12a92e8b90a72849c5b60e"
      url "https://github.com/zasper-io/zasper/releases/download/v#{version}/zasper-webapp-#{version}-linux-amd64.tar.gz"
    end
  end

  name "zasper"
  desc "High Performance IDE for Jupyter Notebooks"
  homepage "https://zasper.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zasper"

  # No zap stanza required

  caveats <<~EOS
    Zasper needs a Jupyter kernel to run notebooks:
      pip install ipykernel
  EOS
end
